import * as RESPONSE_CODES from "./response.code.json";
import * as STATE_CODES from "./state.code.json";
import MIME_TYPE from "./mime-type";

const ROOM = {
	CLIENT_CONNECTING: "clients-connecting"
};

const LANGUAGE_DEFAULT: string = "vi";

const WALLET_TRANS_TYPE = {
	PAY: "PAY",
	CASHIN: "CASHIN",
	CASHOUT: "CASHOUT",
	MERCHANT_WITHDRAW: "MERCHANT_WITHDRAW",
	TRANSFER: "TRANSFER",
	REFUND: "REFUND",
	REFUND_CASHIN: "REFUND_CASHIN",
	TRANSFER_SENDER: "TRANSFER_SENDER",
	TRANSFER_RECEIVER: "TRANSFER_RECEIVER",
	SELL: "SELL",
	MERCHANT_REVENUE: "MERCHANT_REVENUE",
	BUY: "BUY"
};

const REFUND_REQUEST_STATE = {
	SUCCESS: "SUCCESS",
	PAID: "PAID",
	PROCESSING: "PROCESSING",
};

export { LANGUAGE_DEFAULT, RESPONSE_CODES, STATE_CODES, ROOM, MIME_TYPE, WALLET_TRANS_TYPE, REFUND_REQUEST_STATE };
